### ISSUE TITLE
Error 503 when innitiating downloads (downloadcmd)

### ISSUE THREAD

**Issue by sina-mansour** [NDAR/nda-tools#103]
In the past couple of months, I have been unable to download NDA mindar packages. NDA keeps responding "503 Service Temporarily Unavailable" errors. (e.g. when using shared data packages for HCP development data)

I wanted to ask if this is a scheduled/anticipated maintenance outage, or if I need to change something on my side (e.g. an issue with my script/credentials).

Many thanks

**Comment by sina-mansour** [comment]
P.S. This is the traceback of the error:

Traceback (most recent call last):
  File "/mountpoint/code/environments/pymc_env/bin/downloadcmd", line 8, in <module>
    sys.exit(main())
  File "/mountpoint/code/environments/pymc_env/lib/python3.10/site-packages/NDATools/clientscripts/downloadcmd.py", line 182, in main
    s3Download.start()
  File "/mountpoint/code/environments/pymc_env/lib/python3.10/site-packages/NDATools/Download.py", line 198, in start
    package_resource = self.get_package_info()
  File "/mountpoint/code/environments/pymc_env/lib/python3.10/site-packages/NDATools/Download.py", line 1010, in get_package_info
    tmp = get_request(url, auth=self.auth, deserialize_handler=DeserializeHandler.none)
  File "/mountpoint/code/environments/pymc_env/lib/python3.10/site-packages/NDATools/Utils.py", line 304, in get_request
    return _send_prepared_request(req.prepare(), timeout=timeout, deserialize_handler=deserialize_handler,
  File "/mountpoint/code/environments/pymc_env/lib/python3.10/site-packages/NDATools/Utils.py", line 266, in _retry
    tmp = func(*args, **kwargs)
  File "/mountpoint/code/environments/pymc_env/lib/python3.10/site-packages/NDATools/Utils.py", line 293, in _send_prepared_request
    tmp = session.send(prepped, timeout=timeout)
  File "/mountpoint/code/environments/pymc_env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mountpoint/code/environments/pymc_env/lib/python3.10/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='nda.nih.gov', port=443): Max retries exceeded with url: /api/package/1185264 (Caused by ResponseError('too many 503 error responses'))

**Comment by gregmagdits** [comment]
NDA temporarily suspended packaging and downloading functionality for end users. We do not yet have a timeline for when this capability will be re-established.

**Comment by jrussell9000** [comment]
Does NDA plan on making alternate data access methods available for investigators? Say, investigators with NIMH grants explicitly dependent on data from NDA? If so, when?

**Comment by gregmagdits** [comment]
No, data access is suspended for all investigators until further notice, however, you may contact ndahelp@mail.nih.gov to see if other accommodations can be made.

**Comment by jrussell9000** [comment]
Just to update any other investigators who may come across this thread - the end result of e-mailing to ask for the data (as suggested above) was the following reply:

_Thank you for contacting the NDA Help Desk. NDA is unable to release data at this time. Our packaging and downloading services, the Download Manager tool, and miNDAR databases are currently unavailable. We don’t have an estimated time for when these services will be restored. 
 
Please check the NDA website (nda.nih.gov) next week for updates. We'll remove the banner once the services are back online._

**Comment by debosarkar** [comment]
The download services have been fully restored and you should be able to download data as normal
