### ISSUE TITLE
Invalid password error

### ISSUE THREAD

**Issue by spurani** [NDAR/nda-tools#51]
Hello NDA team,

I am getting an invalid password error though I am using the exact credentials for logging successfully into NDA login.gov account.

**Comment by gregmagdits** [comment]
Its confusing but the credentials that are used to login to the NDA website are different from the ones to login to the Download Manager. The credentials needed to login to the DM are your old NDA specific username and password. If you do not remember what they are, you will need to login to the website (using your login.gov creds) and click the 'Reset Password' blue button. After that you will be able to login to the Download Manager using the password you specified.

**Comment by spurani** [comment]
ok so I reset the password. But when I am trying to update the password with python
```
>>> import keyring
>>> keyring.set_password("system", "username", "password")
```
its giving me error 

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.8/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownMethod] ("No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/secrets/collection/login",)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.8/site-packages/secretstorage/collection.py", line 177, in get_default_collection
    return Collection(connection)
  File "/home/user/anaconda3/lib/python3.8/site-packages/secretstorage/collection.py", line 45, in __init__
    self._collection.get_property('Label')
  File "/home/user/anaconda3/lib/python3.8/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/home/user/anaconda3/lib/python3.8/site-packages/secretstorage/util.py", line 52, in send_and_get_reply
    raise ItemNotFoundException('Item does not exist!') from resp
secretstorage.exceptions.ItemNotFoundException: Item does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.8/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
  File "/home/user/anaconda3/lib/python3.8/site-packages/secretstorage/collection.py", line 179, in get_default_collection
    return create_collection(connection, 'Default', 'default', session)
  File "/home/user/anaconda3/lib/python3.8/site-packages/secretstorage/collection.py", line 159, in create_collection
    raise PromptDismissedException('Prompt dismissed.')
secretstorage.exceptions.PromptDismissedException: Prompt dismissed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/lib/python3.8/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/home/user/anaconda3/lib/python3.8/site-packages/keyring/backends/chainer.py", line 56, in set_password
    return keyring.set_password(service, username, password)
  File "/home/user/anaconda3/lib/python3.8/site-packages/keyring/backends/SecretService.py", line 87, in set_password
    collection = self.get_preferred_collection()
  File "/home/user/anaconda3/lib/python3.8/site-packages/keyring/backends/SecretService.py", line 63, in get_preferred_collection
    raise InitError("Failed to create the collection: %s." % e)
keyring.errors.InitError: Failed to create the collection: Prompt dismissed..

**Comment by tashrifbillah** [comment]
Echoing Greg's comment from my personal ticket with him:

> Right.....It's confusing but the credentials that are used to login to the NDA website are different from the ones to login to the Download Manager. The credentials needed to login to the DM are your old NDA specific username and password. If you do not remember what they are, you will need to login to the website and click the 'Reset Password' blue button. After that you will be able to login to the Download Manager using the new password. 

My old password worked as expected. For future readers, I want to illustrate that Greg meant this blue button:

![image](https://user-images.githubusercontent.com/35086881/201166806-77758018-6645-4129-883e-4bd975a715b1.png)

**Comment by liningpan** [comment]
Are you using a headless Linux machine?
