### ISSUE TITLE
Unclear Error when non-existent package requested

### ISSUE THREAD

**Issue by pvandyken** [NDAR/nda-tools#60]
Python Version: 3.10
nda-tools Version: 0.2.22

The following error prints out after attempting to download a non-existent package (I was mistakenly using the package name rather than the id):

```bash
>>> downloadcmd -dp foobar -d some_dir --workerThreads 1

Running NDATools Version 0.2.22
-u/--username argument not provided. Using default value of 'pvandyk2' which was saved in /home/.../.NDATools/settings.cfg

Getting Package Information...
Traceback (most recent call last):
  File "/home/.../.local/bin/downloadcmd", line 8, in <module>
    sys.exit(main())
  File "/home/.../nda-tools/lib/python3.10/site-packages/NDATools/clientscripts/downloadcmd.py", line 195, in main
    s3Download.start()
  File "/home/.../nda-tools/lib/python3.10/site-packages/NDATools/Download.py", line 183, in start
    package_resource = self.get_package_info()
  File "/home/.../nda-tools/lib/python3.10/site-packages/NDATools/Download.py", line 1011, in get_package_info
    tmp = get_request(url, auth=self.auth, deserialize_handler=DeserializeHandler.none)
  File "/home/.../nda-tools/lib/python3.10/site-packages/NDATools/Utils.py", line 269, in get_request
    return _send_prepared_request(req.prepare(), timeout=timeout, deserialize_handler=deserialize_handler, error_handler=error_handler)
  File "/home/.../nda-tools/lib/python3.10/site-packages/NDATools/Utils.py", line 240, in _retry
    tmp = func(*args, **kwargs)
  File "/home/.../nda-tools/lib/python3.10/site-packages/NDATools/Utils.py", line 263, in _send_prepared_request
    error_handler(tmp)
  File "/home/.../nda-tools/lib/python3.10/site-packages/NDATools/Utils.py", line 71, in print_and_exit
    message = r.json()['message']
KeyError: 'message'
```

If I print out `r.json()` in the final function in the trace (`print_and_exit`), I get the following:

```
{'timestamp': 1673456604119, 'status': 400, 'error': 'Bad Request', 'path': '/api/package/foobar'}
```

These 400 errors should be caught and lead to some `requested package does not exist` error.

**Comment by pvandyken** [comment]
Ideally, since I presume the id needs to be a number, there should be some validation of the value passed to `-dp` ensuring it looks like a number, printing some sort of `-dp must be a number` error when invalid.

**Comment by gregmagdits** [comment]
agreed. Ill create an internal work ticket and try and get it in the next release

**Comment by gregmagdits** [comment]
Latest release (0.2.23) includes the validation for the -dp arg along with an updated description in the output of the --help command to clarify the command syntax. Closing issue
