### ISSUE TITLE
vtcmd hangs after returning a "UnicodeEncodeError"

### ISSUE THREAD

**Issue by holland-reece** [NDAR/nda-tools#74]
vtcmd hangs after returning a "UnicodeEncodeError." I made sure the CSV was saved as a UTF-8 CSV. I just installed nda-tools for the first time so I also made sure that python and all other dependencies are up-to-date. Running Mac Ventura 13.5 OS. Full output below. Any help would be greatly appreciated!

######################### Begin terminal output #########################

bash-5.2$ python -m NDATools.clientscripts.vtcmd '/Users/****/NDA_data_upload/7-15-23/ER_R01_RSdata/mri_template_07152023.csv'
Running NDATools Version 0.2.25
-u/--username argument not provided. Using default value of '****' which was saved in /Users/****/.NDATools/settings.cfg

Validating files...
  0%|                                                                                                                                               | 0/1 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/****/envs/nda_upload/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/****/.local/lib/python3.11/site-packages/NDATools/Validation.py", line 486, in run
    response = post_request(self.api_scope, data, timeout=self.validation_timeout, headers = {'content-type':'text/csv'}, auth=self.auth)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/****/.local/lib/python3.11/site-packages/NDATools/Utils.py", line 276, in post_request
    return _send_prepared_request(req.prepare(), timeout=timeout, deserialize_handler=deserialize_handler, error_handler=error_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/****/.local/lib/python3.11/site-packages/NDATools/Utils.py", line 239, in _retry
    tmp = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/****/.local/lib/python3.11/site-packages/NDATools/Utils.py", line 262, in _send_prepared_request
    tmp = session.send(prepped, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/****/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/****/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/****/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/****/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/****/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/****/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/****/lib/python3.11/http/client.py", line 1331, in _send_request
    body = _encode(body, 'body')
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/****/lib/python3.11/http/client.py", line 166, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufeff' in position 0: Body ('\ufeff') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
  0%|

**Comment by gregmagdits** [comment]
It sounds like you have a Byte-Order-mark in your file (https://www.pgdp.net/wiki/Byte-order_mark). If you remove it and rerun the command it should resolve the error. If you need help removing the BOM from your file, send an email to ndahelp@mail.nih.gov, attach your file and we will help you remove it

**Comment by holland-reece** [comment]
Thank you! This solves the problem!
