### ISSUE TITLE
Seems to require python 3?

### ISSUE THREAD

**Issue by alexlicohen** [NDAR/nda-tools#9]
downloadcmd crashes on python 2:
`Traceback (most recent call last):
File "/Users/alex/anaconda/bin/downloadcmd", line 7, in <module>
from NDATools.clientscripts.downloadcmd import main
File "/Users/alex/anaconda/lib/python2.7/site-packages/NDATools/clientscripts/downloadcmd.py", line 7, in <module>
from NDATools.Download import Download
File "/Users/alex/anaconda/lib/python2.7/site-packages/NDATools/Download.py", line 94
print(*args, **kwargs)
^
SyntaxError: invalid syntax`

works in python 3...

**Comment by obenshaindw** [comment]
@alexlicohen I think the latest release fixes the python2 incompatibilities. Would you mind trying again from python2.7 with the latest version?
